Support for RxJS 7.0 and Angular 13
stalniy/casl pull request #580
Opened 2021-12-21 13:00 UTC by jochenjonc

Upgrade of the peerDependecies to be able to support Angular 13 and RxJS 7.

I looked at the peerDependecies used by Angular in their repo, https://github.com/angular/components/blob/12.2.x/packages.bzl.

I hope this change is enough, I'm not familiar with pnmn and did not succeed in building the project on my machine.

2021-12-21 13:32 UTC, stalniy requested changes

2021-12-21 13:32 UTC, stalniy commented on packages/casl-angular/package.json
>    "devDependencies": {
in devDependencies you need to update `rxjs`, so then when test pass I will know it uses the correct version of rxjs

2021-12-21 13:32 UTC, stalniy commented on packages/casl-angular/package.json
> +    "@angular/core": "^12.0.0 || ^13.0.0-0",
I'm not sure it works properly with Angular v13. You need to update dev deps  angular version to ensure that it's true

2021-12-22 10:37 UTC, jochenjonc commented
@stalniy can you have a look at the failing test? I'm a bit stuck on it.

2021-12-23 23:57 UTC, stalniy commented
I’ll take a look tomorrow

2022-04-22 18:28 UTC, b-johnse commented
bump

2022-04-22 20:59 UTC, stalniy commented
Tests are not passing. Additionally I’d like somebody to check that [this casl example](https://github.com/stalniy/casl-examples/tree/master/packages/angular-todo) works properly with rxjs 7, angular 13 and updated version of casl

I don’t have laptop right now and will not have one for the next few weeks. We have a war in Ukraine and sadly… my family was shelled. currently casl is  the smallest of my problems. 

So, go ahead and do extra work

2022-05-15 15:25 UTC, b-johnse commented
@stalniy I hope you are doing okay! 
I'm using in production with ng13.3 and rxjs 7.5.5 by using --legacy-peer-deps when i `npm i` so no functional change is required

@jochenjonc  if you need I can try taking a look at this to get tests passing

2022-06-14 11:14 UTC, stalniy commented
close in favor of #632

2022-06-14 11:14 UTC, closed without merging